### ISSUE TITLE
pip install fails for missing README

### ISSUE THREAD

**Issue by k0s** [nschloe/frentos#3]
```
(Ebeneezer)# pip install frentos
Collecting frentos
  Using cached frentos-0.1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/69/p1yp189j2370p9k2cfwffcww0000gn/T/pip-build-5RqjG6/frentos/setup.py", line 46, in <module>
        long_description=read('README.rst'),
      File "/private/var/folders/69/p1yp189j2370p9k2cfwffcww0000gn/T/pip-build-5RqjG6/frentos/setup.py", line 16, in read
        encoding='utf-8'
      File "/Users/jehammel/src/Ebeneezer/lib/python2.7/codecs.py", line 884, in open
        file = __builtin__.open(filename, mode, buffering)
    IOError: [Errno 2] No such file or directory: '/private/var/folders/69/p1yp189j2370p9k2cfwffcww0000gn/T/pip-build-5RqjG6/frentos/README.rst'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/69/p1yp189j2370p9k2cfwffcww0000gn/T/pip-build-5RqjG6/frentos/
```
I was mostly checking out the project for curiousity, but thought you should know.

**Comment by nschloe** [comment]
Thanks for the report! Fixed now.
